vars:
  - top: ../..
stages:
  download-from-nomis:
    cmd: python download-from-nomis-api.py
    deps:
      - download-from-nomis-api.py
    outs:
      - ${top}/data/raw/lfs_by_pcon.csv:
          cache: false
  process-latest-by-pcon:
    cmd: papermill --no-progress-bar --no-report-mode latest-by-pcon.ipynb ${top}/output/labour-market-latest-by-pcon.ipynb
    deps:
      - latest-by-pcon.ipynb
      - ${top}/data/raw/lfs_by_pcon.csv
    outs:
      - ${top}/data/processed/labour-market/labour_market_by_pcon.parquet:
          cache: false
          persist: false
      - ${top}/data/processed/labour-market/labour_market_by_pcon.csv:
          cache: false
          persist: false

  download-x10:
    cmd: PYTHONPATH=${top} python download-x10.py
    frozen: true
    deps:
      - download-x10.py
    outs:
      - ${top}/data/raw/x10.xlsx:
          cache: false
  process-x10:
    frozen: true
    cmd: papermill process-x10.ipynb ${top}/output/process-x10.ipynb
    deps:
      - process-x10.ipynb
      - ${top}/data/raw/x10.xlsx
    outs:
      - ${top}/data/processed/x10.csv:
          cache: false
      - ${top}/data/metadata/codes/x10-codes.csv:
          cache: false
